on: [push]

name: build

jobs:
  build:
    name: Rust build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check system
        run: |
          lscpu && free -h

      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build --release

      - name: Check build size and compress
        run: |
          ls -lh target/release/tired_server
          curl -O https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz
          tar -xf upx-4.0.2-amd64_linux.tar.xz
          ./upx-4.0.2-amd64_linux/upx --ultra-brute target/release/tired_server
          ls -lh target/release/tired_server

